### ISSUE TITLE
Dash or underscore

### ISSUE THREAD

**Issue by swillner** [ISI-MIP/isimip-protocol-3#25]
Hi, I am planning to use the attributes for derived output netcdfs. For attribute names, the html files use dashes (e.g. "climate-scenario") whereas the json files use underscore (e.g. "climate_scenario"). Not sure if both variants are intended. Which version should I use for netcdf attributes? Cheers!

**Comment by jochenklar** [comment]
Hi @swillner, if you add netcdf attributes, please use underscores. We do not require, e.g. climate_scenario in the header, but if you want to add it feel free to do so. We only require contact and institution (see also https://www.isimip.org/protocol/preparing-simulation-files/#file-formats-and-meta-data). Our quality control and publication pipelines use the filename to extract the information we need.

**Comment by swillner** [comment]
great, thanks! 
currently working with @jvolkholz on derived output regarding river floods. as derived-output this will add even more potential attributes, so just relying on filenames makes little sense in our case, hence the attributes. once we have the chain cleaned up, we will contact you (@jochenklar) again if it makes sense to add schemas for the additional attributes.

**Comment by swillner** [comment]
btw, i much appreciate the protocol standardization! ;)
